//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FabrykaSPTI_PJ.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelFabrykiContainer : DbContext
    {
        public ModelFabrykiContainer()
            : base("name=ModelFabrykiContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hala> HalaSet { get; set; }
        public virtual DbSet<Maszyna> MaszynaSet { get; set; }
        public virtual DbSet<Operator> OperatorSet { get; set; }
    }
}
